### ISSUE TITLE
How about custom field?

### ISSUE THREAD

**Issue by thuongqbd** [writesdown/app-cms#1]
Thanks for nice work. I have a question. How do I do to add custom field for each post type or post?

**Comment by 13nightevil** [comment]
For custom field for each post-type is not ready and is being developed now, along with the development of the theme. thanks

**Comment by 13nightevil** [comment]
I try what you've done on my application installed on localhost.
On the backend I add new category and post.
Afterward, I go to the frontend and click on the new category link and it work fine.
