### ISSUE TITLE
Demo account is not working

### ISSUE THREAD

**Issue by rinodung** [writesdown/app-cms#2]
Hi!
I login by admin: http://democms.writesdown.com/admin/site/login superadmin/superadmin, but it not working...
![login](https://cloud.githubusercontent.com/assets/7805715/8816188/774349e2-304d-11e5-8c13-1b38478b48d6.png)

**Comment by 13nightevil** [comment]
You have to register first with your own username and password. User: superadmin and pass: superadmin used for newly installed applications through the composer.

**Comment by rinodung** [comment]
Thanks for your response. I live this cms like wordpress + yii2. It's awesome
