### ISSUE TITLE
Media Upload Error

### ISSUE THREAD

**Issue by binarysilo** [writesdown/app-cms#6]
Whenever I try to upload a media file, I receive an error,

exception 'yii\base\ErrorException' with message 'mkdir(): Permission denied' in /home/site

**Comment by 13nightevil** [comment]
I've updated common\components\MediaUploadHandler by changing

``` php
if (!is_dir($uploadDir)) {
     mkdir($uploadDir, $this->getOption('mkdir'), 'true');
}
```

to

``` php
if (!is_dir($uploadDir)) {
     mkdir($uploadDir, $this->getOption('mkdir_mode'), 'true');
}
```

It should work fine now.
